//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceService.Models
{
  using System.Data.Entity;
  using System.Data.Entity.Infrastructure;

  public partial class FinanceContainer : DbContext
    {
        public FinanceContainer()
            : base("name=FinanceContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Plan> PlanSet { get; set; }
        public virtual DbSet<TargetCategory> TargetCategorySet { get; set; }
        public virtual DbSet<Transaction> TransactionSet { get; set; }
    }
}
